export const COORDINATE_SIZE = 16;
export const GAME_CANVAS_SIZE = 640;
export const BACKGROUND_CANVAS_SIZE = GAME_CANVAS_SIZE + COORDINATE_SIZE * 2;
export const CELL_COUNT = 6;
export const CELL_SIZE = GAME_CANVAS_SIZE / CELL_COUNT;
export const TOTAL_CELL_COUNT = CELL_COUNT ** 2;
export const FRAME_SIZE = 128;
